{"hierarchy":{"paths":[["doc:\/\/co.pointfree.VaporRouting\/documentation\/NIOCore","doc:\/\/co.pointfree.VaporRouting\/documentation\/NIOCore\/ByteToMessageDecoderError"]]},"variants":[{"paths":["\/documentation\/niocore\/bytetomessagedecodererror\/datareceivedinerrorstate(_:_:)"],"traits":[{"interfaceLanguage":"swift"}]}],"sections":[],"abstract":[{"type":"text","text":"More data has been received by a "},{"code":"ByteToMessageHandler","type":"codeVoice"},{"type":"text","text":" despite the fact that an error has previously been"},{"type":"text","text":" "},{"type":"text","text":"emitted. The associated "},{"type":"codeVoice","code":"Error"},{"type":"text","text":" is the error previously emitted and the "},{"type":"codeVoice","code":"ByteBuffer"},{"type":"text","text":" is the extra data that has"},{"type":"text","text":" "},{"type":"text","text":"been received. The common cause for this error to be emitted is the user not having torn down the "},{"type":"codeVoice","code":"Channel"},{"type":"text","text":" "},{"text":"after previously an ","type":"text"},{"type":"codeVoice","code":"Error"},{"text":" has been sent through the pipeline using ","type":"text"},{"type":"codeVoice","code":"fireErrorCaught"},{"text":".","type":"text"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/co.pointfree.VaporRouting\/documentation\/NIOCore\/ByteToMessageDecoderError\/dataReceivedInErrorState(_:_:)"},"schemaVersion":{"major":0,"patch":0,"minor":3},"metadata":{"modules":[{"name":"NIOCore"}],"externalID":"s:7NIOCore25ByteToMessageDecoderErrorO014dataReceivedInF5StateyACs0F0_p_AA0B6BufferVtcACmF","role":"symbol","symbolKind":"case","roleHeading":"Case","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"dataReceivedInErrorState","kind":"identifier"},{"text":"(","kind":"text"},{"text":"Error","preciseIdentifier":"s:s5ErrorP","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"ByteBuffer","preciseIdentifier":"s:7NIOCore10ByteBufferV","kind":"typeIdentifier"},{"kind":"text","text":")"}],"title":"ByteToMessageDecoderError.dataReceivedInErrorState(_:_:)"},"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["Linux"],"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"dataReceivedInErrorState","kind":"identifier"},{"text":"(","kind":"text"},{"text":"Error","kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP"},{"text":", ","kind":"text"},{"identifier":"doc:\/\/co.pointfree.VaporRouting\/documentation\/NIOCore\/ByteBuffer","text":"ByteBuffer","kind":"typeIdentifier","preciseIdentifier":"s:7NIOCore10ByteBufferV"},{"text":")","kind":"text"}],"languages":["swift"]}]}],"references":{"doc://co.pointfree.VaporRouting/documentation/NIOCore/ByteToMessageDecoderError/dataReceivedInErrorState(_:_:)":{"url":"\/documentation\/niocore\/bytetomessagedecodererror\/datareceivedinerrorstate(_:_:)","type":"topic","abstract":[{"text":"More data has been received by a ","type":"text"},{"type":"codeVoice","code":"ByteToMessageHandler"},{"type":"text","text":" despite the fact that an error has previously been"},{"type":"text","text":" "},{"type":"text","text":"emitted. The associated "},{"code":"Error","type":"codeVoice"},{"type":"text","text":" is the error previously emitted and the "},{"code":"ByteBuffer","type":"codeVoice"},{"type":"text","text":" is the extra data that has"},{"type":"text","text":" "},{"type":"text","text":"been received. The common cause for this error to be emitted is the user not having torn down the "},{"code":"Channel","type":"codeVoice"},{"type":"text","text":" "},{"type":"text","text":"after previously an "},{"code":"Error","type":"codeVoice"},{"type":"text","text":" has been sent through the pipeline using "},{"code":"fireErrorCaught","type":"codeVoice"},{"type":"text","text":"."}],"identifier":"doc:\/\/co.pointfree.VaporRouting\/documentation\/NIOCore\/ByteToMessageDecoderError\/dataReceivedInErrorState(_:_:)","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"dataReceivedInErrorState"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP","text":"Error"},{"kind":"text","text":", "},{"kind":"typeIdentifier","preciseIdentifier":"s:7NIOCore10ByteBufferV","text":"ByteBuffer"},{"kind":"text","text":")"}],"title":"ByteToMessageDecoderError.dataReceivedInErrorState(_:_:)","kind":"symbol","role":"symbol"},"doc://co.pointfree.VaporRouting/documentation/NIOCore":{"kind":"symbol","url":"\/documentation\/niocore","title":"NIOCore","role":"collection","type":"topic","identifier":"doc:\/\/co.pointfree.VaporRouting\/documentation\/NIOCore","abstract":[]},"doc://co.pointfree.VaporRouting/documentation/NIOCore/ByteBuffer":{"abstract":[{"type":"codeVoice","code":"ByteBuffer"},{"type":"text","text":" stores contiguously allocated raw bytes. It is a random and sequential accessible sequence of zero or"},{"type":"text","text":" "},{"type":"text","text":"more bytes (octets)."}],"role":"symbol","kind":"symbol","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"ByteBuffer"}],"navigatorTitle":[{"kind":"identifier","text":"ByteBuffer"}],"type":"topic","identifier":"doc:\/\/co.pointfree.VaporRouting\/documentation\/NIOCore\/ByteBuffer","url":"\/documentation\/niocore\/bytebuffer","title":"ByteBuffer"},"doc://co.pointfree.VaporRouting/documentation/NIOCore/ByteToMessageDecoderError":{"url":"\/documentation\/niocore\/bytetomessagedecodererror","type":"topic","abstract":[{"text":"Common errors thrown by ","type":"text"},{"type":"codeVoice","code":"ByteToMessageDecoder"},{"type":"text","text":"s."}],"navigatorTitle":[{"text":"ByteToMessageDecoderError","kind":"identifier"}],"identifier":"doc:\/\/co.pointfree.VaporRouting\/documentation\/NIOCore\/ByteToMessageDecoderError","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ByteToMessageDecoderError","kind":"identifier"}],"title":"ByteToMessageDecoderError","kind":"symbol","role":"symbol"}}}